# Generated by Django 4.2.13 on 2024-07-08 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxurytravels', '0003_add_frequent_flyer_number_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Default Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 7, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_number',
            field=models.CharField(default='Default Passport Number', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='000-000-00000', max_length=15),
            preserve_default=False,
        ),
    ]
